version: '3.9'

services:
  node:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: node
    volumes:
      - ./api:/home/node/app/api
    working_dir: /home/node/app/api
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: ["npx", "ts-node", "app.ts"]
    networks:
      - routing
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.f1-api.rule=Host(`blue-api.devprod.fr`)'
      - 'traefik.http.routers.f1-api.entrypoints=websecure'
      - 'traefik.http.routers.f1-api.tls.certresolver=myresolver'
networks:
   routing:
      external: true
      default: