version: '3.9'

services:
  node:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: node
    volumes:
      - ./api:/home/node/app/api
    working_dir: /home/node/app/api
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: ["npx", "ts-node", "app.ts"]
